FROM golang:1.21.1-alpine3.18 as build
WORKDIR /gin_gorm_auth
COPY . .
RUN go mod download \
    --go install github.com/swaggo/swag/cmd/swag@latest \
    --go install github.com/joho/godotenv/cmd/godotenv@latest \
    --swag init \
    --go build
FROM alpine:latest
WORKDIR /gin_gorm_auth
COPY --from=build /gin_gorm_auth /gin_gorm_auth
CMD ["./gin_and_gorm"]