version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.yaml
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    restart: on-failure
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - PORT=${PORT}
      - SECERET=${SECERET}
      - APP_HOST=${APP_HOST}

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080