version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    command: air cmd/main.go 
  db:
  image: postgres:alphine
  environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}
  ports:
    -5432:5432

    
