basePath: /
definitions:
  models.Body:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:4000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Add weapon
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/models.Body'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Post a weapon
  /signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: Add weapon
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/models.Body'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Post a weapon
  /validate:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get userjkhvlkjdshakjfhaskjlfhsadkjhfdsakljhdskajfkajs
securityDefinitions:
  OAuth2Password:
    flow: password
    tokenUrl: /login
    type: oauth2
swagger: "2.0"
