apiVersion: v1 
kind: Service
metadata:
  name: go-app-service 
  labels:
    name: go-app-service
    app: demo-voting-app

spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30005
  selector:
    name: go-app-pod
    app: gin_gorm_auth