apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    name: postgres-deploy
    app: gin_gorm_auth

spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: gin_gorm_auth
    
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: gin_gorm_auth

    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
